### ISSUE TITLE
Failed creating ModAPI instance from DLL 1z.dll

### ISSUE THREAD

**Issue by Xianlao-Jushi** [Naiwazi/NaiwaziBot#1]

**Comment by Andersonfeng** [comment]
一样
[MODS] Failed creating ModAPI instance from DLL 1z.dll

**Comment by Xianlao-Jushi** [comment]
> 一样 [MODS] Failed creating ModAPI instance from DLL 1z.dllz
这个是A19的Bot与服务端版本不符

**Comment by Xianlao-Jushi** [comment]
> INF [MODS] Found ModAPI in 1z.dll, creating instance ERR [MODS] Failed creating ModAPI instance from DLL 1z.dll EXC VTable setup of type NaiwaziBotLancher.API failed
> 
> 不知道为啥加载不了
